//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESCHANGE.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorties
    {
        public int srt_ID { get; set; }
        public Nullable<System.DateTime> srt_Date { get; set; }
        public string srt_Refference { get; set; }
        public Nullable<int> srt_Quantite { get; set; }
        public string srt_Note { get; set; }
        public Nullable<int> vl_ID { get; set; }
        public Nullable<int> pies_ID { get; set; }
    
        public virtual Pieces Pieces { get; set; }
        public virtual Vehicules Vehicules { get; set; }
    }
}
